/* Generated by AN DISI Unibo */ 
package it.unibo.coldstorageservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Coldstorageservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 val ticketList = listOf<Ticket>() 
			   val currentWeight = 0 
			   val maxWeight = 100
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("coldstorageservice starts")
						forward("domove", "domove(home)" ,"transporttrolley" ) 
						forward("domove", "domove(indoor)" ,"transporttrolley" ) 
						answer("showticketrequest", "showticketvalid", "showticketvalid(arg)"   )  
						answer("showticketrequest", "showticketinvalid", "showticketinvalid(arg)"   )  
						answer("showticketrequest", "ticketrequestaccepted", "ticketrequestaccepted(arg)"   )  
						answer("showticketrequest", "ticketrequestrefused", "ticketrequestrefused(arg)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("waitclientrequest") { //this:State
					action { //it:State
						CommUtils.outblack("$name | waiting the client request...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="elabTicketRequest",cond=whenRequest("ticketrequest"))
					transition(edgeName="t07",targetState="elabShowTicketRequest",cond=whenRequest("showticketrequest"))
					transition(edgeName="t08",targetState="elabStoreFood",cond=whenRequest("storefood"))
				}	 
				state("elabTicketRequest") { //this:State
					action { //it:State
						  val ticket = it.unibo.coldstorageservice.Ticket("aaa",Instant.now().epochSecond,3)
									
						answer("ticketrequest", "ticketrequestaccepted", "ticketrequestaccepted("aaa")"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("elabShowTicketRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("showticketrequest(TICKET,FW)"), Term.createTerm("showticketrequest(TICKET,FW)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val currentTime = Instant.now().epochSecond 
										   	   val idTicket = payloadArg(0)
										   	   
										   	   for (ticket in ticketList){
										   	   	  //ciclo for per trovare il biglietto del driver nella lista
										   	   }
										   	   
										   	   val ticketValid = (currentTime - ticket.creationTime) > TIMEMAX
										   	   if(ticketValid){
										   	   	
										   	   
								answer("showticketrequest", "showticketvalid", "showticketvalid("valid")"   )  
								 } 
											   else{
											   	
											   	
								answer("showticketrequest", "showticketinvalid", "showticketinvalid("invalid")"   )  
								 }  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("elabStoreFood") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storefood(FW)"), Term.createTerm("storefood(FW)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val foodWeight = payloadArg()
													
								forward("domove", "domove(indoor)" ,"transporttrolley" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_elabStoreFood", 
				 	 					  scope, context!!, "local_tout_coldstorageservice_elabStoreFood", 2500.toLong() )
					}	 	 
					 transition(edgeName="t29",targetState="moveRobotHome",cond=whenTimeout("local_tout_coldstorageservice_elabStoreFood"))   
					transition(edgeName="t210",targetState="elabStoreFood",cond=whenRequest("storefood"))
				}	 
				state("moveRobotHome") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
			}
		}
}
