/* Generated by AN DISI Unibo */ 
package it.unibo.ctxcoldstorageservice
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "192.168.1.141", this, "raspberry.pl", "sysRules.pl", "ctxcoldstorageservice"
	)
}

